### ISSUE TITLE
How to make hot reload

### ISSUE THREAD

**Issue by donadoo** [ReactUnity/core#16]
using ```yarn start``` command to start, can only see changes from ```http://localhost:3000```, changes could not apply to mobile device. Is there any other steps?
![image](https://user-images.githubusercontent.com/44422450/128012129-dd46b467-61c6-48c5-a9aa-2abd82a6f590.png)

**Comment by KurtGokhan** [comment]
Two steps are required:
- The "Dev server" option is normally ignored in build. You must set `REACT_ALLOW_DEVSERVER` build flags to enable it.
- Your PC must be on the same network as the mobile device. And you need to write your PC's IP address instead of `localhost`.

The IP address is usually shown when you do `yarn start`:

![image](https://user-images.githubusercontent.com/6034931/128015498-a201ad1e-3b41-43ec-bb76-9a0bcb668b65.png)


Note: Instead of the first step, you can also set Type to URL and write the IP address there.

**Comment by donadoo** [comment]
@KurtGokhan thanks.
by the way, how to set ```REACT_ALLOW_DEVSERVER ``` build flags

**Comment by KurtGokhan** [comment]
You need to go to "Project Settings > Player > Android > Other Settings > Scripting Define Symbols" and add it there:

![image](https://user-images.githubusercontent.com/6034931/128021152-fba578d4-b462-4153-9ffa-123c920fd0cf.png)

You can learn more about custom build flags (define symbols) it in the Unity documentation [here](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

**Comment by donadoo** [comment]
@KurtGokhan thanks, already worked
