### ISSUE TITLE
How to replace JINT to QuickJS

### ISSUE THREAD

**Issue by donadoo** [ReactUnity/core#20]
JINT run slow, lots of memory, How to use QuickJS instead of JINT

**Comment by KurtGokhan** [comment]
I need to write an adapter for it to be usable with React Unity. But I don't know if that is possible because we need .NET interoperability and QuickJS may not be written with that capability.

Right now, instead of Jint, you can use ClearScript in  Windows, Mac and Linux standalone (Mono). It uses Chrome's V8 engine. I am planning to extend support for ClearScript to Android and WebGL but this is low priority for now, and I am not sure if it will work.

Let's keep this issue open. I will check if it's easy to integrate QuickJS.

**Comment by pbgodwin** [comment]
I was browsing some repos and happened to stumble across this: https://github.com/vmas/QuickJS.NET

Not sure how feature complete this library is, but maybe it can help with this issue?

**Comment by KurtGokhan** [comment]
Thanks for the suggestion. Jint and ClearScript provide ways to naturally interact with C# code from Javascript. Bringing QuickJS.Net to that capability would be a huge undertaking.

The best thing to do for a faster Android runtime is to build [ClearScript](https://github.com/microsoft/ClearScript) for Android, and I decided to do it. I don't know when I will do it though.

**Comment by KurtGokhan** [comment]
ClearScript now works for Android Mono as an alternative to Jint. I cannot vouch for its performance yet but I guess it is better than Jint. Jint can be disabled explicitly with `REACT_DISABLE_JINT` define if you want to cut down `apk` size.

QuickJS will be hard to implement so closing this issue.
