### ISSUE TITLE
fontWeight style does not appear to work

### ISSUE THREAD

**Issue by amagee** [ReactUnity/core#26]
If I try `{{fontWeight: "bold"}}` or a number, say, `{{fontWeight: 900}}`, these are ignored and the text is just displayed at the regular weight. I've noticed that `fontStyle: "italic"` does work as expected though.

I'm not entirely sure I know what I'm talking about but it seems the `fontWeight` property on the TextMeshPro component is being used. The [docs for this property](https://docs.unity3d.com/Packages/com.unity.textmeshpro@1.0/api/TMPro.TMP_Text.html#TMPro_TMP_Text_fontWeight) say 

> Control the weight of the font if an alternative font asset is assigned for the given weight in the font asset editor.

so my guess is the reason it's not working is because of the "alternative font asset" requirement. So I'm not sure of a general solution for supporting font weights.

I did notice that `fontStyle` property in the same TextMeshPro class does include options for creating bold text ([link](https://docs.unity3d.com/Packages/com.unity.textmeshpro@1.0/api/TMPro.FontStyles.html)) and this appears to work when I play with it manually in the inspector, so possibly this would be helpful for supporting `{{fontWeight: "bold"}}` at least.

**Comment by KurtGokhan** [comment]
Fixed in 0.4.10

`bold` in `fontStyle` and in `fontWeight` are different. I made an exception that when `bold` typeface does not exist in the font asset, it will set `bold` in `fontStyle`. You can also use number values now (i.e. 700) which was not possible before.

You may also want to know that you can provide multiple comma-separated values to font style like `fontStyle: 'italic, bold, smallcaps'`. Right now this is different than browser CSS but in the future I may implement `text-transform`, `font-variant` and other text related properties instead of using `font-style` for everything.
