### ISSUE TITLE
Forward slash in css is ignored creating invalid names

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#45]
Forward slash `\` should  escape the next character in CSS file

**Source:** Repository
**Branch:** Main
**Renderer:** ReactUnityUIDocument

**Example:** 
```
.button {
    color: white;
    background-color: rgb(59 130 246);
}

.hover\:button:hover {
    background-color: rgb(212, 0, 231);
}
```

Should be used as: 
```
<button className="button hover:button">
     Text
</button>
```

**Expected result:** Button should change color on hover
**Actual result:** Nothing happens

**Comment by KurtGokhan** [comment]
Our CSS parser is an ad-hoc parser and there can be bugs like this, unfortunately. This one is fixed on main branch now. But I doubt this is the end of Tailwind related bugs. Let's collect Tailwind bugs under this issue.

**Comment by Muchaszewski** [comment]
I hope this is the last one for a while. 

Property `font-size: 100%` results in size of the text to be 1px. Instead of 16px.

**Comment by KurtGokhan** [comment]
Also fixed.

**Comment by Muchaszewski** [comment]
`::before` and `::after` are considered elements with computed size (font size seems to be directly related to their size) even if they are empty.
Tailwind uses them to remove some default HTML styling form browser. 

**In browser**
With before and after:
![image](https://user-images.githubusercontent.com/5092066/165110215-956d720d-6ded-471e-bc9a-c6356f6a7bc3.png)
Without
![image](https://user-images.githubusercontent.com/5092066/165110311-c9b05fa5-a524-436b-b86d-fe6ad28f183b.png)

**In Unity**
![image](https://user-images.githubusercontent.com/5092066/165110430-9375e9e7-5e3e-48ee-a119-b6c234075df9.png)
_before, _text and _after have computed height of 20
![image](https://user-images.githubusercontent.com/5092066/165110722-2f34420a-3acd-4732-887a-a5f750e1e6d6.png)

**Comment by Muchaszewski** [comment]
By default in HTML width of the element is assumed "0" unless it has some content. For example text. Then this text decides the size of that content.

Here whereas height is somewhat correct, width is assumed to be the width of the screen. This is easily fixable with styling, but might cause some issues for pure conversions from some examples

**Comment by Muchaszewski** [comment]
Border radius (and maybe other properties?) Do not accept rem as a unit. 
So eg: `border-radius: 0.25rem` doesn't work, whereas identical in function `border-radius: 4px` works as intended. Those two styles should behave identicaly

**Comment by KurtGokhan** [comment]
@Muchaszewski  some of these are inevitable differences between web and ReactUnity. Web has several different [layout modes](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Introduction) such as inline, block, flex, grid, table etc. For web the default is block/inline layout. ReactUnity only has flex.  And ReactUnity's implementation of flex is also different from web. Also we have different defaults. For example the `flex-direction` is `column` by default. ReactUnity uses the defaults of [Yoga](https://github.com/facebook/yoga), the layout engine we use. 

Tailwind isn't aware of that and so that is why you are having problems. The before/after issue can be solved by setting the buttons `flex-direction` to `row`. And as you said you have incorrect width because element's width is stretched by default. You can change defaults in your CSS as:

```css
* {
  flex-direction: row;
  align-items: start;
  justify-content: start;
}
```

We could also code different layout modes in the future but this is the least priority right now. Although web has so many different layouts, most of them can be emulated with flexbox layout. There are cases when each layout has its advantages though. For example, inline/block layout is best when text is more prevalent, or table layout is good for showing tabular data. For now, users will need to be aware that 1-to-1 conversion from web to ReactUnity is not possible and they need to watch out for layout differences.

One thing we can fix is setting the width/height to 0 if text content is empty. I will check how it works.

As for border-radius, I will fix it. I think it can because it is a shorthand and our shorthand implementation is not too good to accept different units yet. Separate properties may work.
