### ISSUE TITLE
onMouseDown, onPointerDown and probably more events do not work as intended

### ISSUE THREAD

**Issue by Muchaszewski** [ReactUnity/core#83]
I wanted to experiment with the drag-and-drop system and couldn't find a way to work out how onDragEnter and onDragExit works. Probably this has nothing to do with what I want and it will just accept something being dragged into the screen I assume. But wanting to implement my own handler, I encountered an event issue.

**`div` example**
```
<div                            
    onPointerDown={() => {console.log("onPointerDown")}}  //DOESN'T WORK
    onPointerUp={() => {console.log("onPointerUp")}}  //DOESN'T WORK
    onPointerOut={() => {console.log("onPointerOut")}}  //WORK
    onPointerEnter={() => {console.log("onPointerEnter")}}  //WORK
    onPointerLeave={() => {console.log("onPointerLeave")}}  //WORK
    onPointerCancel={() => {console.log("onPointerCancel")}}  //DOESN'T WORK
    onPointerOver={() => {console.log("onPointerOver")}}  //WORK
    onMouseDown={() => {console.log("onMouseDown")}}  //DOESN'T WORK
    onMouseUp={() => {console.log("onMouseUp")}}   //DOESN'T WORK
    >
    some content
</div>
```

**`button` example**
```
<button
    onPointerDown={() => {console.log("onPointerDown")}}  //DOESN'T WORK
    onPointerUp={() => {console.log("onPointerUp")}}  //WORK
    onPointerOut={() => {console.log("onPointerOut")}}  //WORK
    onPointerEnter={() => {console.log("onPointerEnter")}}  //WORK
    onPointerLeave={() => {console.log("onPointerLeave")}}  //WORK
    onPointerCancel={() => {console.log("onPointerCancel")}}  //DOESN'T WORK
    onPointerOver={() => {console.log("onPointerOver")}}  //WORK
    onMouseDown={() => {console.log("onMouseDown")}}  //DOESN'T WORK
    onMouseUp={() => {console.log("onMouseUp")}}  //WORK
    >
    some content
</button>
```

**Issue**
Some of the events are not called, and those are different for buttons and divs.

**Version**
React Unity 0.14.3
UIDocument with QuickJS

**Comment by KurtGokhan** [comment]
I tried this with UIToolkit (I think that is how you tested it too). For `div`, it works as expected:

![image](https://user-images.githubusercontent.com/6034931/218344009-450e371f-b44c-45a6-8c24-61fac01d6fce.png)

Except `onPointerCancel` because I don't know how to test it. Also `onPointerUp` and `onMouseUp` don't fire if you leave the element when holding the mouse down.

For `button` it is as you said. `onPointerDown` doesn't work probably because Unity handles that internally. According to [this forum thread](https://forum.unity.com/threads/pointerdownevent-on-buttons-not-working.1211238/) the event should be registered with `TrickleDown`, and ReactUnity does not do that. It is similar to `capture` in browsers. So I will add a `capture` variant to every event.

I don't know why the `div` works different for you. Can you see any difference that may cause it?

**Comment by Muchaszewski** [comment]
From what I tested it behaves like that when the `button` is a child of a div. It looks like the events are handled by the button instead of a div, and since you do not perform TrickleDown the event is probably stopped by the button, just registering an empty event.

```
<div onPointerDown={() => {console.log("onPointerDown")}}>
  <button>
    Button
  </button>
</div>
```

**Comment by KurtGokhan** [comment]
The newest version of core and renderer now allow `TrickleDown` variant of all events like `onPointerDownCapture`

**Comment by Muchaszewski** [comment]
That works! Thank you :) 

But I have to argue if that would not be confusing to have so many different events. At the end of the day should perform the same exact action, and there is almost no difference for the end user.

**Comment by KurtGokhan** [comment]
React for Web also has the same naming convention for capture events (for example `onClick` and `onClickCapture`). Since UIToolkit is inspired by HTML, I think it is acceptable to have this. There may be significant differences for the end user, and I can't know which variant the user needs. So, I think it is better to present both options.

Closing this.
